USE database_name;

CREATE TABLE STORAGE(
   ID INT,
        CONSTRAINT STORAGE_PK PRIMARY KEY (ID),
        FORMAT_SUPPORTED VARCHAR(50) NOT NULL,
        STORAGE_COUNTRY VARCHAR(70),
        MAX_SIZE INT
);