USE database_name;

CREATE TABLE PRODUCTHB(
     ID INT AUTO_INCREMENT,
     CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
     NAME VARCHAR(20) NOT NULL,
     DESCRIPTON LONGTEXT,
     PRICE INT NOT NULL
);


