USE database_name;

CREATE TABLE ROOM(
    ID INT AUTO_INCREMENT,
    CONSTRAINT ROOM_ID PRIMARY KEY (ID),
    NUMBER_OF_GUESTS INT,
    PRICE  DOUBLE(10,2),
    BREKFAST_INCLUDED INT,
    PETS_ALLOWED INT,
    DATE_AVAILABLE_FROM DATE,
    HOTELS_ID INT NOT NULL,
    CONSTRAINT HOTELS_FK FOREIGN KEY (HOTELS_ID) REFERENCES HOTELS(ID)
);

