USE database_name;

CREATE TABLE HOTELFPR(
     ID INT AUTO_INCREMENT,
     CONSTRAINT HOTELFPR_ID PRIMARY KEY (ID),
     NAME VARCHAR (30),
     COUNTRY VARCHAR (40),
     CITY VARCHAR (40),
     STREET VARCHAR (50)
);
