USE database_name;

CREATE TABLE ROOMFPR(
    ID INT AUTO_INCREMENT,
    CONSTRAINT ROOMFPR_ID PRIMARY KEY (ID),
    NUMBER_OF_GUESTES INT,
    PRICE  DOUBLE(10,2),
    BREKFAST_INCLUDED BOOLEAN,
    PETS_ALLOWED BOOLEAN,
    DATE_AVAILABLE_FROM DATE,
    HOTELFPR_ID INT NOT NULL,
    CONSTRAINT HOTELFPR_FK FOREIGN KEY (HOTELFPR_ID) REFERENCES HOTELFPR(ID)
);