USE database_name;

CREATE TABLE USERFPR(
    ID INT AUTO_INCREMENT,
    CONSTRAINT USERFPR_ID PRIMARY KEY (ID),
    USER_NAME VARCHAR(40),
    PASSWORD VARCHAR(20),
    COUNTRY VARCHAR(40),
    USER_TYPE ENUM('ADMIN','USER')
);

ALTER TABLE USERFPR MODIFY USER_NAME VARCHAR(50) UNIQUE;
ALTER TABLE USERFPR MODIFY USER_TYPE ENUM('ADMIN','USER') NOT NULL;
ALTER TABLE USERFPR MODIFY USER_TYPE VARCHAR(20);
ALTER TABLE USERFPR MODIFY USER_TYPE ENUM('ADMIN','USER') NOT NULL;

