USE database_name;

CREATE TABLE ORDERFPR(
     ID INT AUTO_INCREMENT,
     CONSTRAINT ORDERFPR_ID PRIMARY KEY (ID),
     USERFPR_ID INT NOT NULL,
        CONSTRAINT USERFPR_FK FOREIGN KEY (USERFPR_ID) REFERENCES USERFPR(ID),
     ROOMFPR_ID INT NOT NULL,
        CONSTRAINT ROOMFPR_FK FOREIGN KEY (ROOMFPR_ID) REFERENCES ROOMFPR(ID),
     DATE_FROM DATE,
     DATE_TO DATE,
     MONEY_PAID DOUBLE(10,2)
);


